CREATE TABLE IF NOT EXISTS `order` (
    `order_id` INT AUTO_INCREMENT,
    `cart_id` varchar(20) NOT NULL,
    `shipping_provider_id` INT NOT NULL,
    `shipping_price` INT NOT NULL,
    `product_price` INT NOT NULL,
    `track_code` varchar(300),
    `address_id` INT NOT NULL,
    `first_name` varchar(20) NOT NULL,
    `last_name` varchar(300),
    `phone` varchar(20),
    `address` varchar(300),
    `city` varchar(20),
    `province` varchar(20),
    `zip_code` varchar(10),
    `u_id` INT NOT NULL,
    `status` ENUM('pending', 'processing', 'shipped', 'cancelled'),
    `payment_id` INT,
    `payment_method` ENUM('transfer', 'cod'),
    `context` varchar(300),
    `createtime` datetime DEFAULT CURRENT_TIMESTAMP,
    `end_process_time` datetime,
    PRIMARY KEY(`order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;